-- MySQL Script generated by MySQL Workbench
-- Sun Sep 27 10:32:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lmui_website
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lmui_website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lmui_website` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `lmui_website` ;

-- -----------------------------------------------------
-- Table `lmui_website`.`about_lmui`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`about_lmui` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`about_lmui` (
  `about_lmui_title` VARCHAR(90) NOT NULL,
  `message` JSON NULL COMMENT 'message is json with the following schema {message: []}',
  PRIMARY KEY (`about_lmui_title`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`about_lmui_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`about_lmui_history` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`about_lmui_history` (
  `history_year` VARCHAR(5) NOT NULL,
  `history_discription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`history_year`, `history_discription`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`about_pillars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`about_pillars` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`about_pillars` (
  `title` VARCHAR(20) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`title`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`about_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`about_staff` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`about_staff` (
  `staff_matricule` VARCHAR(20) NOT NULL,
  `staff_name` VARCHAR(45) NOT NULL,
  `staff_title` VARCHAR(45) NOT NULL,
  `staff_bio` MEDIUMTEXT NULL,
  `staff_image` VARCHAR(200) NULL,
  PRIMARY KEY (`staff_matricule`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`admission_deadline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`admission_deadline` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`admission_deadline` (
  `round` VARCHAR(60) NOT NULL,
  `date` DATE NOT NULL,
  `note` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`round`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`admission_steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`admission_steps` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`admission_steps` (
  `number` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`number`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`campus_gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`campus_gallery` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`campus_gallery` (
  `gallery_label` VARCHAR(50) NOT NULL,
  `gallery_size` CHAR(2) NOT NULL,
  `gallery_pattern` VARCHAR(45) NOT NULL,
  `gallery_image` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`gallery_label`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`faq` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`faq` (
  `question` VARCHAR(100) NOT NULL,
  `answer` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`question`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`hero_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`hero_stats` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`hero_stats` (
  `value` INT NOT NULL,
  `suffix` CHAR(1) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `prefix` CHAR(1) NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`landmark_schools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`landmark_schools` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`landmark_schools` (
  `schools_name` VARCHAR(200) NOT NULL,
  `schools_short_name` VARCHAR(10) NOT NULL,
  `school_slug` VARCHAR(45) NOT NULL,
  `school_tag_line` VARCHAR(45) NOT NULL,
  `school_logo` VARCHAR(200) NOT NULL,
  `schools_description` JSON NOT NULL COMMENT 'description is a json object with schema as follows {description: []}\nthe discription list or array is a list of the description paragraphs in string',
  `schools_stat` JSON NOT NULL COMMENT 'school_stat is a json object with the following schema {value: \"int value\', label: \'string for it label\'}',
  `school_pattern` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`schools_short_name`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`news` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`news` (
  `slug` VARCHAR(45) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `dek` VARCHAR(200) NOT NULL,
  `catergory` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `read_time` VARCHAR(15) NOT NULL,
  `body` JSON NOT NULL COMMENT 'body is a list of paragraphs in a json object {body: []}',
  `image` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`slug`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`programs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`programs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`programs` (
  `slug` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `schools_short_name` VARCHAR(10) NOT NULL,
  `degree_level` VARCHAR(45) NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `programscol` VARCHAR(45) NOT NULL,
  `sumarry` VARCHAR(300) NOT NULL,
  `highlights` JSON NOT NULL COMMENT 'a json object listing the paragraphs of all program highllights {highlights: []}',
  `outcomes` JSON NULL COMMENT 'a json object listing all the outcomes {outcomes: []}',
  PRIMARY KEY (`slug`),
  INDEX `fk_programs_landmark_schools_idx` (`schools_short_name` ASC) VISIBLE,
  CONSTRAINT `fk_programs_landmark_schools`
    FOREIGN KEY (`schools_short_name`)
    REFERENCES `lmui_website`.`landmark_schools` (`schools_short_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`secondary_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`secondary_stats` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`secondary_stats` (
  `value` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `suffix` CHAR(1) NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lmui_website`.`testimonials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lmui_website`.`testimonials` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lmui_website`.`testimonials` (
  `quote` VARCHAR(300) NOT NULL,
  `student_name` VARCHAR(45) NOT NULL,
  `detail` VARCHAR(200) NULL,
  `student_image` VARCHAR(200) NULL,
  PRIMARY KEY (`quote`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
